preprocess:
  test_size: 0.2
  random_state: 45
  scaling_out: models/scaling_model.pkl

train:
  target_col: chance_of_admit
  n_estimators: 100
  max_depth: 6

paths:
  model_out: models/model.pkl
  metrics_out: metrics/metrics.json

mlflow:
  tracking_uri: http://localhost:5000
  experiment_name: university_prediction
